### ISSUE TITLE
Cloudtest may run two tests on one cluster 

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/cloudtest#17]
<img width="662" alt="Screenshot 2020-01-31 at 22 41 30" src="https://user-images.githubusercontent.com/47595664/73552737-5c64d680-447b-11ea-8e0d-867954c2ca2a.png">

**Comment by artem-belov** [comment]
azure-1 was restarted before running two tests

**Comment by artem-belov** [comment]
https://circleci.com/gh/networkservicemesh/networkservicemesh/120648

**Comment by haiodo** [comment]
I fixed something like this some time ago.

**Comment by denis-tingajkin** [comment]
I guess we need also to add a regression test.
