### ISSUE TITLE
Directive `only-run` doesn't work

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/cloudtest#23]
## Expected

If cloudtest config has `only-run` tests then cloudtest will run only these tests.

## Actual

Cloudtest ignores `only-run` tests

## Commit
https://github.com/networkservicemesh/networkservicemesh/commit/09166bfbb98dac4144781e0f8ab4a5a257966895
https://github.com/networkservicemesh/networkservicemesh/pull/2115/commits/8837ac234f5e5cb7606c4735d388c7ca75bdd85c (take a look at CI result)

**Comment by denis-tingajkin** [comment]
@alex-yust do we have any tests for directive `only-run`?

**Comment by alex-yust** [comment]
> @alex-yust do we have any tests for directive `only-run`?

nope
