### ISSUE TITLE
How to create two clusters one after another and run tests on both cluster after the first cluster is setup with necessary components

### ISSUE THREAD

**Issue by Shridhar-2205** [networkservicemesh/cloudtest#53]
I want to create two kind clusters one after another and interacting with each other, is it possible to run go tests after that.
Based on my understanding the clusters are created/deleted as well as the tests are executed independently. 
I want to run multiple cluster tests.
Please suggest any tags/fields. 
Thanks.

**Comment by denis-tingaikin** [comment]
I think you could be interested in https://github.com/networkservicemesh/integration-interdomain-k8s/blob/main/.cloudtest.yaml

**Comment by Shridhar-2205** [comment]
> I think you could be interested in https://github.com/networkservicemesh/integration-interdomain-k8s/blob/main/.cloudtest.yaml

I tried this, but the clusters are running in parallel manner. I have to install some specific components on the first cluster in prepare stage ,after that I have to install components in second cluster through prepare stage after the components installation in first cluster via prepare stage is finished successfully. After that I have to run go tests on first cluster only, not on the second cluster. Do you have such examples?
